PNC\ChiroBundle\Entity\Biometrie:
    type: entity
    table: chiro.subpr_observationtaxon_biometrie
    schema: chiro
    #repositoryClass: PNC\ChiroBundle\Repositories\BiometrieRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fk_cotx_id:
            type: integer
        cbio_age_id:
            type: integer
            nullable: true
        cbio_sexe_id:
            type: integer
            nullable: true
        cbio_ab:
            type: float
            nullable: true
        cbio_poids:
            type: float
            nullable: true
        cbio_d3mf1:
            type: float
            nullable: true
        cbio_d3f2f3:
            type: float
            nullable: true
        cbio_d3total:
            type: float
            nullable: true
        cbio_d5:
            type: float
            nullable: true
        cbio_cm3sup:
            type: float
            nullable: true
        cbio_cm3inf:
            type: float
            nullable: true
        cbio_cb:
            type: float
            nullable: true
        cbio_lm:
            type: float
            nullable: true
        cbio_oreille:
            type: float
            nullable: true
        cbio_commentaire:
            type: text 
            nullable: true
        meta_create_timestamp: 
            type: date
        meta_update_timestamp:
            type: date
        meta_numerisateur_id:
            type: integer
            nullable: true

