PNC\ChiroBundle\Entity\SiteAmenagements:
    type: entity
    table: chiro.rel_chirosite_thesaurus_amenagement
    schema: chiro
    id:
        site_id:
            type: integer
        thesaurus_id:
            type: integer

