PNC\ChiroBundle\Entity\SiteMenaces:
    type: entity
    table: chiro.rel_chirosite_thesaurus_menace
    schema: chiro
    id:
        site_id:
            type: integer
        thesaurus_id:
            type: integer

