PNC\ChiroBundle\Entity\SiteView:
    type: entity
    table: chiro.vue_chiro_site
    schema: chiro
    repositoryClass: PNC\ChiroBundle\Repositories\SiteView
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        bs_nom:
            type: text
        bs_code:
            type: text
        bs_date:
            type: date
        geom:
            type: json_array
        nom_observateur:
            type: text
        bs_obr_id:
            type: integer
        bs_type_id:
            type: integer
        type_lieu:
            type: text
        bs_description:
            type: text
        cis_frequentation:
            type: text
        cis_menace:
            type: text
        cis_menace_cmt:
            type: text
        cis_actions:
            type: text
        site_fichiers:
            type: json_array
        cis_contact_nom:
            type: text
        cis_contact_prenom:
            type: text
        cis_contact_adresse:
            type: text
        cis_contact_code_postal:
            type: text
        cis_contact_ville:
            type: text
        cis_contact_telephone:
            type: text
        cis_contact_portable:
            type: text
        cis_contact_commentaire:
            type: text
        cis_site_actif:
            type: boolean
        dern_obs:
            type: date
        nb_obs:
            type: integer
        meta_create_timestamp: 
            type: date
        meta_update_timestamp:
            type: date
        meta_numerisateur_id:
            type: integer
        ref_commune:
            type: json_array


